-----------------------------------------------------------------------------
-- Module      : problem12
-- Copyright   : (c) 2010 David M. Rosenberg
-- License     : BSD3
-- 
-- Maintainer  : David Rosenberg <rosenbergdm@uchicago.edu>
-- Stability   : experimental
-- Portability : portable
-- Created     : 03/21/10
-- 
-- Description :
--    DESCRIPTION HERE.
-----------------------------------------------------------------------------



-----------------------------------------------------------------------------
-- The sequence of triangle numbers is generated by adding the natural     -- 
-- numbers. So the 7^(th) triangle number would be                         --
-- 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:           --
--                                                                         --
--           1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...                      --
--                                                                         --
--                                                                         --
-- Let us list the factors of the first seven triangle numbers:            --
--                                                                         --
--      1: 1                                                               --
--      3: 1,3                                                             --
--      6: 1,2,3,6                                                         --
--     10: 1,2,5,10                                                        --
--     15: 1,3,5,15                                                        --
--     21: 1,3,7,21                                                        -- 
--     28: 1,2,4,7,14,28                                                   --
--                                                                         --
-- We can see that 28 is the first triangle number to have over five       --
-- divisors.                                                               --
--                                                                         --
-- What is the value of the first triangle number to have over five        --
-- hundred divisors?                                                       --
-----------------------------------------------------------------------------

import Math.Divisible
import Data.List

numFactors :: Int -> Int
numFactors x = max 2 (foldl (\acc x -> acc * (mult x + 1)) 1 (getFactors x))

triNumberBuilder' :: Int -> [Int]
triNumberBuilder' n = triBuilder' n [1]

triBuilder' :: Int -> [Int] -> [Int]
triBuilder' n xs
  | length xs == n  = xs
  | otherwise       = triBuilder' n (concat [xs, [maximum xs + length xs + 1]])

triNumbers :: (Integral a) => a -> [a]
triNumbers n = map (\x -> round $ fromIntegral ((x + 1) * (x + 2)) / 2) [1..n]

isTriangular :: Int -> Bool
isTriangular x = x' - ((round . sqrt . fromIntegral) x')^2 == 0
  where x' = 8 * x + 1


